In [3]:
import numpy as np

A = np.array([[1,2,3],[1,2,3]])
print(A)

[[1 2 3]
 [1 2 3]]


In [28]:
B = np.array([[1,1,1],[2,2,2],[1,2,3]])
print(B)
print(B.shape) #rows and column
m, n = B.shape
print(m,n)

[[1 1 1]
 [2 2 2]
 [1 2 3]]
(3, 3)
3 3


In [10]:
C = A.dot(B) #Matrix Multiplication
print(C)

[[ 8 11 14]
 [ 8 11 14]]


In [15]:
D = np.array([[1,1,5],[0,8,0]])
C = A+D
print(C)

[[ 2  3  8]
 [ 1 10  3]]


In [16]:
print(C.transpose())

[[ 2  1]
 [ 3 10]
 [ 8  3]]


In [17]:
#Access elements
print(A[0][0],A[-1][-1],A[1][0])

1 3 1


In [21]:
#Access columns
print(A[:,2])

[3 3]


In [22]:
#Access rows
print(A[1,:])

[1 2 3]


In [23]:
#Rank of matrix

A = np.array([[1,2,3],[2,3,1]])
m,n = A.shape
tempArray = []

for i in range(0,m):
    tempArray.append(A[i,:])
    #print(tempArray)

pivot1, pivot2 = 0,0

pivot1 = tempArray[0]


#setting pivot values i,j
row = 4
i=0

for j in range(0,row-1):
    #print(i,j)
    #print(i+1,j)
    #print("\n")
    i+=1
    

In [98]:
#PIVOT MISSED
def pivotmulti(r1,r2,p):
    print(r1,r2)
    r1 = r1*p[1]
    r2 = r2*p[0]
    return r1,r2

def difference(r1,r2):
    r2 = r1-r2
    return r1,r2

A = np.array([[1,2,3],[2,3,1],[1,2,1]])
row,col = A.shape
i = 0
pivot = []
for j in range(0,row-1):
    #print(i,j)
    #print(i+1,j)
    print("\n")
    
    pivot = [A[i][j],A[i+1][j]]
    print("Pivot", pivot)
    A[j,:],A[j+1,:]=pivotmulti(A[j,:],A[j+1,:],pivot)
    print("Pivot Multiplied",A[j,:],A[j+1,:])
    
    A[j,:],A[j+1,:]=difference(A[j,:],A[j+1,:])
    print("Updated",A[j,:],A[j+1,:])
    
    
    i+=1



Pivot [1, 2]
[1 2 3] [2 3 1]
Pivot Multiplied [2 4 6] [2 3 1]
Updated [2 4 6] [0 1 5]


Pivot [1, 2]
[0 1 5] [1 2 1]
Pivot Multiplied [ 0  2 10] [1 2 1]
Updated [ 0  2 10] [-1  0  9]


In [80]:
def difference(r1,r2):
    r2 = r1-r2
    return r1,r2

def pivotmulti(r1,r2,p):
    print(r1,r2)
    r1 = r1*p[1]
    r2 = r2*p[0]
    return r1,r2
    
    
row1 = np.array([2,1,5])
row2 = np.array([3,6,1])
p = [2,3]
row1, row2 = pivotmulti(row1,row2,p)
print(row1,row2)

r1,r2 = difference(row1,row2)
print(r1,r2)

[2 1 5] [3 6 1]
[ 6  3 15] [ 6 12  2]
[ 6  3 15] [ 0 -9 13]


In [99]:
def pivotmulti(r1,r2,p):
    print(r1,r2)
    r1 = r1*p[1]
    r2 = r2*p[0]
    return r1,r2

def difference(r1,r2):
    r2 = r1-r2
    return r1,r2

A = np.array([[1,2,3],[2,3,1],[1,2,1]])
row,col = A.shape
i = 0
pivot = []
for j in range(0,row-1):
    #print(i,j)
    #print(i+1,j)
    print("\n")
    
    pivot = [A[i][j],A[i+1][j]]
    print("Pivot", pivot)
    A[j,:],A[j+1,:]=pivotmulti(A[j,:],A[j+1,:],pivot)
    print("Pivot Multiplied",A[j,:],A[j+1,:])
    
    A[j,:],A[j+1,:]=difference(A[j,:],A[j+1,:])
    print("Updated",A[j,:],A[j+1,:])
    
    
    i+=1



Pivot [1, 2]
[1 2 3] [2 3 1]
Pivot Multiplied [2 4 6] [2 3 1]
Updated [2 4 6] [0 1 5]


Pivot [1, 2]
[0 1 5] [1 2 1]
Pivot Multiplied [ 0  2 10] [1 2 1]
Updated [ 0  2 10] [-1  0  9]


In [136]:
A = np.array([[1,2,3],[2,3,1],[1,2,1]])
row,col = A.shape
pivotindex = []
for i in range(0,row):
    for j in range(0,col):
        if i<=j:
            print(j,i)
            for k in range(0,row):
                pivotindex.append([j,i])

print(pivotindex)

0 0
1 0
2 0
1 1
2 1
2 2
[[0, 0], [0, 0], [0, 0], [1, 0], [1, 0], [1, 0], [2, 0], [2, 0], [2, 0], [1, 1], [1, 1], [1, 1], [2, 1], [2, 1], [2, 1], [2, 2], [2, 2], [2, 2]]


......



Rank of a Matrix




......

In [58]:
import numpy as np

class RankofMatrix():
    
    def __init__(self,A):
        self.A = A
        self.row, self.col = A.shape
        self.c = 0
        self.tempc = 0
        self.flag = True
        print("Row, Col = ",self.row, self.col)
        print("Matrix is = ",self.A)
        print("------------------")
                    
    def checkforoverlap(self):
        if self.c:
            if self.c == self.tempc+1:
                self.flag = True
                #self.tempc = self.c
            else:
                self.flag = False
        
                    
    def setpivots(self,r1,r2):
        for i in range(0,self.col):
            print(self.flag,r2[i])
            if r2[i] and self.flag:
                p1 = r1[i]
                p2 = r2[i]
                #print("i, p1, p2 = ",i,p1,p2)
                break
            self.c += 1
            print("Check for overlap",self.tempc,self.c)
            rank_matrix.checkforoverlap()
            
        print("True count=",self.c)
      
        return p1,p2
          
    def multidiffer(self,r1,r2):
        print("passed row",r1,r2)
        t = r1
        p1, p2 = rank_matrix.setpivots(r1,r2)
        print("pivot are ",p1,p2)
        r1 = p2*r1
        r2 = p1*r2
        r2 = r2-r1
        return t,r2
        

    def mainalgo(self):
        k = 0
        while self.row-k:
            print("------------------")
            print("kth pass=",k)
            print("------------------")
            for i in range(0,self.row-1):
                try:
                    r1, r2 = rank_matrix.multidiffer(self.A[k], self.A[i+k+1])
                    print("Updated",r1,r2)
                    print("            ")
                    self.A[k] = r1
                    self.A[i+k+1] = r2
                except:
                    pass
            k+=1
            self.tempc = self.c
            print("\nTemp Count=", self.tempc)
            
        print("       RESULT        ")
        print(self.A)
        print("LAST count=",self.c)
        
    
if __name__ == '__main__':
    A = np.array([[1,2,3],[2,3,1],[1,2,1]]) #passed
    B = np.array([[2,2,2],[2,5,1],[2,1,3]]) #passed
    C = np.array([[1,2,2],[2,4,4],[3,6,6]]) #passed
    D = np.array([[1,2,3],[2,4,6],[2,0,7]]) #Failed
    rank_matrix = RankofMatrix(D)
    rank_matrix.mainalgo()


Row, Col =  3 3
Matrix is =  [[1 2 3]
 [2 4 6]
 [2 0 7]]
------------------
------------------
kth pass= 0
------------------
passed row [1 2 3] [2 4 6]
True 2
True count= 0
pivot are  1 2
Updated [1 2 3] [0 0 0]
            
passed row [1 2 3] [2 0 7]
True 2
True count= 0
pivot are  1 2
Updated [1 2 3] [ 0 -4  1]
            

Temp Count= 0
------------------
kth pass= 1
------------------
passed row [0 0 0] [ 0 -4  1]
True 0
Check for overlap 0 1
True -4
True count= 1
pivot are  0 -4
Updated [0 0 0] [0 0 0]
            

Temp Count= 1
------------------
kth pass= 2
------------------

Temp Count= 1
       RESULT        
[[1 2 3]
 [0 0 0]
 [0 0 0]]
LAST count= 1
